"""
memory
变量的内存机制
string是不可变对象,python有个intern机制,简单来说就是维护一个字典
字典维护者键值对,每次创建新字符串都会和这个字典做比较,如果重复就直接用指针引用
所以下面的str是相同的地址
Author:LXQing
Date:2023/6/28
"""
str1='hello'
str2='hello'
print(id(str1))
print(id(str2))
